### ISSUE TITLE
Logging option

### ISSUE THREAD

**Issue by karllhughes** [rosszurowski/micro-airtable-api#9]
Another feature I'd like to help with is adding a configuration option to allow stdout/stderr logging. It helps me identify improper use by frontend clients, and is handy for analytics purposes so I can see where the most load is.

I'm thinking of adding a `LOGGING=true` option to the env options to enable it and using [debug](https://github.com/visionmedia/debug) to implement it.

Feedback is welcome.

**Comment by rosszurowski** [comment]
Logging can be an opinionated topic. I know people who prefer formats like [bunyan](https://www.npmjs.com/package/bunyan) or [ndjson](http://ndjson.org/), and others who like the simplicity of plain text logs.

I'm open to providing logging as a part of this tool, even turning it on by default, as long as we don't lock folks into a certain format.

An approach I'm fond of is splitting this library into two pieces: a JS API and a CLI.

The JS API would return a function to use with `http.createServer`, `koa`, `express`, `hapi` or any other server framework. This would give users the flexibility to use their own logging middleware. On the other hand, the CLI would provide a quick-and-easy way to get started, with smart defaults for a web server and logging.

[`micro-analytics`](https://github.com/micro-analytics/micro-analytics-cli), [`micro`](https://github.com/zeit/micro) and [`serve`](https://github.com/zeit/serve) are some libraries that also took this approach.

Anyone who wanted to handle more advanced use-cases could use the JS API. Folks who just want something simple could do a one-command deploy to `now` using the CLI.

**Comment by karllhughes** [comment]
That's a cool idea. I agree that keeping a core part of this library very open-ended and "lighter" is probably a good approach, and then either building extensions or a "heavy" version that adds nice to have features.

**Comment by karllhughes** [comment]
Now that we've broken the CLI and JS app up, I am going to close this. To your point @rosszurowski, logging is a very opinionated topic, so if people want to log requests, they can import the NPM package and choose their own logging strategy.

Unless there's a some reason that the core library needs to change for logging to work (which I don't see), closing this seems right to me.
